name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: hello test
      id: hello-test
      uses: education/autograding-io-grader@v1
      with:
        test-name: hello test
        command: "./hello.sh"
        input: ''
        expected-output: Hello
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        HELLO-TEST_RESULTS: "${{steps.hello-test.outputs.result}}"
      with:
        runners: hello-test
